<?php
session_start();
unset($_SESSION["id"]);
unset($_SESSION["username"]);
unset($_SESSION["fname"]);
unset($_SESSION["email"]);
unset($_SESSION["usertype"]);
header("Location:../../index.html");
?>